codecov:
  enabled: false
  ignore:
    - "src/main/kotlin/openai/clients/data/ChatCompletion.kt"
    - "src/main/kotlin/openai/clients/MockOpenAiClientImpl.kt"
    - "src/main/kotlin/openai/clients/*"