name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Java (Kotlin runs on JVM)
      - name: Set up JDK 20
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '20'

      # Step 3: Cache Gradle dependencies
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Step 4: Run ktlint for code style checks
      - name: Run Ktlint
        run: ./gradlew ktlintCheck

      # Step 5: Run the tests
      - name: Build and run tests
        run: ./gradlew test jacocoTestReport

      # Step 6: Download jacoco-to-lcov-reporter
      - name: Download jacoco-to-lcov-reporter
        run: wget https://raw.githubusercontent.com/davidramos-om/jacoco-lcov/master/jacoco-to-lcov

      # Step 7: Convert the JaCoCo XML report to LCOV format
      - name: Convert JaCoCo XML to LCOV
        run: bash jacoco-to-lcov build/reports/jacoco/test/jacocoTestReport.xml > build/reports/jacoco/test/jacocoTestReport.lcov

      # Step 8: Upload coverage to Coveralls
      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: build/reports/jacoco/test/jacocoTestReport.xml
