name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Java (Kotlin runs on JVM)
      - name: Set up JDK 20
        uses: actions/setup-java@v2
        with:
          java-version: '20'

      # Step 3: Cache Gradle dependencies
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Step 4: Run ktlint for code style checks
      - name: Run Ktlint
        run: ./gradlew ktlintCheck

      # Step 5: Run the tests
      - name: Run tests
        run: ./gradlew test
