name: Ensure PR is linked to an Issue

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-pr:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Run the custom issue-link-checker action
      - name: Check for linked issue
        uses: ./.github/actions/issue-link-checker
        with:
          pattern: 'Closes #\\d+'"