name: Ensure PR is linked to an Issue

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-pr:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Check PR for linked issue using LottieFiles/pr-body-labeler-action
      - name: Check for linked issue
        uses: LottieFiles/pr-body-labeler-action@v1
        with:
          pr-body-keywords: 'Closes #\\d+'  # Pattern to match issue link