name: Ensure PR is linked to an Issue

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-pr:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Use action-pr-body-check to ensure issue is linked
      - name: Check for linked issue
        uses: mszostok/action-pr-body-check@v1
        with:
          pattern: 'Closes #\\d+'  # Pattern to match issue link