name: Ensure PR is linked to an Issue

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-pr:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js (Install dependencies)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Use the correct Node.js version

      # Step 3: Install dependencies for the custom action
      - name: Install dependencies
        run: |
          cd .github/actions/issue-link-checker
          npm install

      # Step 4: Run the custom issue-link-checker action
      - name: Check for linked issue
        uses: ./.github/actions/issue-link-checker
        with:
          pattern: 'Closes #\d+'